### login user
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### create user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "test",
  "password": "test"
}

### create note
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "test",
  "content": "test"
}

### get notes
GET http://localhost:3001/api/notes
Authorization: Bearer <token>

### get users
GET http://localhost:3001/api/users
Authorization: Bearer <token>


### reset db
POST http://localhost:3001/api/testing/reset
